name: Linux ssh (12gb ram / 60gb ssd / 2core / VT-x support)

on: 
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: chuẩn bị phần mềm
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up
          sudo chpasswd runner:123
      - name: đang setup linũ
        uses: mxschmitt/action-tmate@v2
