name: Linux ssh (12gb ram / 60gb ssd / 2core / VT-x support)

on: 
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: chuẩn bị phần mềm
        run: |
          sudo apt-get install tmate
      - name: đang setup linũ
        run: |
          tmate
